#!/usr/bin/env node

/**
 * Converts JSDoc JSON output to Markdown documentation.
 * This script reads JSDoc JSON data and generates a formatted Markdown file.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const classOrder = ['Server', 'Client', 'Message', 'Bundle'];
const functionOrder = ['encode', 'decode'];

function githubAnchor(text) {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^\w\- ]+/g, '')
    .replace(/\s+/g, '-');
}

function runJsdoc() {
  try {
    return execSync('npx jsdoc -X -c jsdoc.json', {
      encoding: 'utf8',
      maxBuffer: 10 * 1024 * 1024
    });
  } catch (error) {
    throw new Error(`Failed to run JSDoc: ${error.message}`, { cause: error });
  }
}

function parseJsdocJson(jsdocJson) {
  try {
    return JSON.parse(jsdocJson);
  } catch (error) {
    throw new Error(`Failed to parse JSDoc JSON output: ${error.message}`, { cause: error });
  }
}

function collectDocs(docs) {
  const classes = {};
  const functions = {};

  docs.forEach(item => {
    if (item.undocumented || item.ignore) return;

    if (item.kind === 'class' && item.classdesc) {
      const classInfo = classes[item.name] || {
        desc: '',
        constructor: null,
        methods: [],
        examples: [],
        augments: []
      };

      classInfo.desc = item.classdesc;
      classInfo.examples = item.examples || [];
      classInfo.augments = item.augments || [];
      classes[item.name] = classInfo;

      if (item.params) {
        classes[item.name].constructor = {
          params: item.params,
          examples: item.examples || []
        };
      }
    } else if (item.kind === 'function' && item.memberof) {
      const className = item.memberof;
      if (!classes[className]) {
        classes[className] = {
          desc: '',
          constructor: null,
          methods: [],
          examples: [],
          augments: []
        };
      }
      classes[className].methods.push(item);
    } else if (item.kind === 'function' && !item.memberof && item.scope === 'global') {
      functions[item.name] = item;
    }
  });

  return { classes, functions };
}

function formatParams(params) {
  if (!params || params.length === 0) return '';

  let result = '\n**Parameters:**\n\n';
  params.forEach(param => {
    const optional = param.optional ? ' (optional)' : '';
    const defaultVal = param.defaultvalue ? ` - Default: \`${param.defaultvalue}\`` : '';
    const types = param.type ? param.type.names.join(' | ') : 'any';
    result += `- \`${param.name}\` *{${types}}*${optional}${defaultVal} - ${param.description || ''}\n`;
  });
  return result;
}

function formatExamples(examples) {
  if (!examples || examples.length === 0) return '';

  let result = '\n**Examples:**\n\n';
  examples.forEach(example => {
    result += '```javascript\n' + example + '\n```\n\n';
  });
  return result;
}

function formatReturns(returns) {
  if (!returns || returns.length === 0) return '';

  const ret = returns[0];
  const types = ret.type ? ret.type.names.join(' | ') : 'any';
  return `\n**Returns:** *{${types}}* - ${ret.description || ''}\n`;
}

function formatThrows(exceptions) {
  if (!exceptions || exceptions.length === 0) return '';

  let result = '\n**Throws:**\n\n';
  exceptions.forEach(ex => {
    const types = ex.type ? ex.type.names.join(' | ') : 'Error';
    result += `- *{${types}}* - ${ex.description || ''}\n`;
  });
  return result;
}

function generateMarkdown(classes, functions) {
  let markdown = `<!-- Generated by JSDoc. Update this documentation by updating the source code. -->

# API Reference

> **⚠️ This file is auto-generated from JSDoc comments in the source code.**  
> To update this documentation, edit the JSDoc comments in the source files and run \`npm run docs\`.

This document provides detailed API reference for all classes, methods, and functions in node-osc.

For usage guides, best practices, and troubleshooting, see the **[Guide](./GUIDE.md)**.

## Table of Contents

`;

  classOrder.forEach(name => {
    if (classes[name]) {
      markdown += `- [${name}](#${githubAnchor(name)})\n`;
      if (classes[name].constructor) {
        markdown += `  - [Constructor](#${githubAnchor(`${name} Constructor`)})\n`;
      }
      classes[name].methods.forEach(method => {
        markdown += `  - [${method.name}()](#${githubAnchor(`${name}.${method.name}()`)})\n`;
      });
    }
  });

  markdown += `- [Low Level Functions](#${githubAnchor('Low Level Functions')})\n`;
  functionOrder.forEach(name => {
    if (functions[name]) {
      markdown += `  - [${name}()](#${githubAnchor(`${name}()`)})\n`;
    }
  });

  markdown += `\n---\n\n`;

  classOrder.forEach(className => {
    const classInfo = classes[className];
    if (!classInfo) return;

    markdown += `## ${className}\n\n`;

    if (classInfo.augments && classInfo.augments.length > 0) {
      markdown += `**Extends:** ${classInfo.augments.join(', ')}\n\n`;
    }

    markdown += `${classInfo.desc}\n`;

    if (classInfo.examples.length > 0 && !classInfo.constructor) {
      markdown += formatExamples(classInfo.examples);
    }

    if (classInfo.constructor) {
      markdown += `\n### ${className} Constructor\n\n`;
      markdown += `Creates a new ${className} instance.\n`;
      markdown += formatParams(classInfo.constructor.params);
      markdown += formatExamples(classInfo.constructor.examples);
    }

    classInfo.methods.forEach(method => {
      markdown += `\n### ${className}.${method.name}()\n\n`;
      markdown += `${method.description || ''}\n`;
      markdown += formatParams(method.params);
      markdown += formatReturns(method.returns);
      markdown += formatThrows(method.exceptions);
      markdown += formatExamples(method.examples);
    });

    markdown += `\n---\n\n`;
  });

  markdown += `## Low Level Functions\n\n`;
  markdown += 'These functions provide low-level access to OSC encoding and decoding for advanced use cases.\n\n';

  functionOrder.forEach(funcName => {
    const func = functions[funcName];
    if (!func) return;

    markdown += `### ${funcName}()\n\n`;
    markdown += `${func.description || ''}\n`;
    markdown += formatParams(func.params);
    markdown += formatReturns(func.returns);
    markdown += formatThrows(func.exceptions);
    markdown += formatExamples(func.examples);
    markdown += '\n';
  });

  return markdown;
}

function main() {
  try {
    const jsdocJson = runJsdoc();
    const docs = parseJsdocJson(jsdocJson);
    const { classes, functions } = collectDocs(docs);
    const markdown = generateMarkdown(classes, functions);
    writeFileSync('docs/API.md', markdown, 'utf8');
    console.log('✅ API documentation generated: docs/API.md');
  } catch (error) {
    console.error(`❌ ${error.message}`);
    process.exit(1);
  }
}

main();
